$path = 'ecommerce1/resources/views/frontEnd/layouts/pages/campaign/campaign.blade.php'
$text = [System.IO.File]::ReadAllText($path)

$replacements = @(
    @{ p='<a href="#features">.*?</a>'; r='<a href="#features">বৈশিষ্ট্য</a>' },
    @{ p='<a href="#faq">.*?</a>'; r='<a href="#faq">প্রশ্নোত্তর</a>' },
    @{ p='<a href="#order">.*?</a>'; r='<a href="#order">অর্ডার</a>' },
    @{ p='\{\{ auth\(''customer''\)->user\(\)->name \}\} .*'; r='{{ auth(''customer'')->user()->name }} এর অ্যাকাউন্ট' },
    @{ p='\{\{ \$campaign_data->hero_badge_text \?\? ''.*?'' \}\}'; r='{{ $campaign_data->hero_badge_text ?? ''✅ খুলনার অরিজিনাল চুই ঝাল'' }}' },
    @{ p='\{\{ \$campaign_data->hero_title \?\? ''.*?'' \}\}'; r='{{ $campaign_data->hero_title ?? ''খুলনার বিখ্যাত চুই ঝাল!'' }}' },
    @{ p='\?\? ''.*?যান.*?'' \}\}'; r='?? ''নিজ হাতে প্রস্তুত ঘানি ভাঙা সরিষার তেল আর বিশেষ মশলার মিশেলে তৈরি আমাদের চুই ঝাল। গরু, খাসি, হাঁস কিংবা মাছ - যেকোনো মাংসের সাথে রান্না করে পেয়ে যান খুলনার আসল স্বাদ।'' }}' },
    @{ p='\{\{ \$campaign_data->hero_list_1 \?\? ''.*?'' \}\}'; r='{{ $campaign_data->hero_list_1 ?? ''হোমমেড - কোন প্রিজারভেটিভ নেই'' }}' },
    @{ p='\{\{ \$campaign_data->hero_list_2 \?\? ''.*?'' \}\}'; r='{{ $campaign_data->hero_list_2 ?? ''খাঁটি চুই গাছ থেকে তৈরি'' }}' },
    @{ p='\{\{ \$campaign_data->hero_list_3 \?\? ''.*?'' \}\}'; r='{{ $campaign_data->hero_list_3 ?? ''ফুড গ্রেড প্যাকেট'' }}' },
    @{ p='\{\{ \$campaign_data->hero_list_4 \?\? ''.*?'' \}\}'; r='{{ $campaign_data->hero_list_4 ?? ''ঘানি ভাঙা সরিষার তেল'' }}' },
    @{ p='\{\{ \$campaign_data->hero_list_5 \?\? ''.*?'' \}\}'; r='{{ $campaign_data->hero_list_5 ?? ''দেশব্যাপী কুরিয়ার ডেলিভারি'' }}' },
    @{ p='\{\{ \$campaign_data->hero_list_6 \?\? ''.*?'' \}\}'; r='{{ $campaign_data->hero_list_6 ?? ''ক্যাশ অন ডেলিভারি'' }}' },
    @{ p='<span class="stars">.*?</span>'; r='<span class="stars">★★★★★</span>' },
    @{ p='\{\{ \$campaign_data->hero_rating_text \?\? ''.*?'' \}\}'; r='{{ $campaign_data->hero_rating_text ?? ''৪.৯/৫ (৪৮৯+ কাস্টমার)'' }}' },
    @{ p='\{\{ \$campaign_data->primary_btn_text \?\? ''.*?'' \}\}'; r='{{ $campaign_data->primary_btn_text ?? ''এখনই অর্ডার করুন'' }}' },
    @{ p='\{\{ \$campaign_data->secondary_btn_text \?\? ''.*?'' \}\}'; r='{{ $campaign_data->secondary_btn_text ?? ''লাইভ রান্না ভিডিও'' }}' },
    @{ p='title=".*?ভিডিও"'; r='title="চুই ঝাল রান্না ভিডিও"' },
    @{ p='\{\{ \$campaign_data->feature_section_title \?\? ''.*?'' \}\}'; r='{{ $campaign_data->feature_section_title ?? ''চুই ঝালের বৈশিষ্ট্যসমূহ'' }}' },
    @{ p='\{\{ \$campaign_data->feature1_title \?\? ''.*?'' \}\}'; r='{{ $campaign_data->feature1_title ?? ''কাঁচা চুই ঝালের আসল ঝাঁজ'' }}' },
    @{ p='\{\{ \$campaign_data->feature1_text \?\? ''.*?'' \}\}'; r='{{ $campaign_data->feature1_text ?? ''খুলনা অঞ্চলের নিরবাচিত চুই গাছের নরম অংশ সংগ্রহ করে...'' }}' },
    @{ p='\{\{ \$campaign_data->feature2_title \?\? ''.*?'' \}\}'; r='{{ $campaign_data->feature2_title ?? ''দীর্ঘদিন ভালো থাকে'' }}' },
    @{ p='\{\{ \$campaign_data->feature2_text \?\? ''.*?'' \}\}'; r='{{ $campaign_data->feature2_text ?? ''ভ্যাকুয়াম প্যাকিং এবং সঠিক ডিহাইড্রেশন থাকার কারণে...'' }}' },
    @{ p='\{\{ \$campaign_data->heading_2 \?\? ''.*?'' \}\}'; r='{{ $campaign_data->heading_2 ?? ''কেন আমাদের প্রোডাক্ট সেরা?'' }}' },
    @{ p='\{\{ \$campaign_data->why1_icon \?\? ''.*?'' \}\}'; r='{{ $campaign_data->why1_icon ?? ''⭐'' }}' },
    @{ p='\{\{ \$campaign_data->why3_text \}\}.*'; r='{{ $campaign_data->why3_text }}।' },
    @{ p='\{\{ \$campaign_data->banner_quote \?\? ''.*?'' \}\}'; r='{{ $campaign_data->banner_quote ?? ''“এমন ঝাঁজে নেই তো তুলনা!”'' }}' },
    @{ p='\{\{ \$campaign_data->banner_subtext \?\? ''.*?'' \}\}'; r='{{ $campaign_data->banner_subtext ?? ''খুলনার অরিজিনাল চুই ঝাল - একবার খেলেই বুঝবেন পার্থক্য'' }}' },
    @{ p='\{\{ \$campaign_data->billing_details \?\? ''.*?'' \}\}'; r='{{ $campaign_data->billing_details ?? ''আমাদের প্যাকগুলো'' }}' },
    @{ p='<h2 class="section-title">.*?গ্যালারি</h2>'; r='<h2 class="section-title">চুই ঝাল গ্যালারি</h2>' },
    @{ p='<h2 class="section-title">অর্ডার করুন .*?</h2>'; r='<h2 class="section-title">অর্ডার করুন এখনই</h2>' },
    @{ p='<span>.*?সিলেক.*?</span>'; r='<span>এই প্যাকটি সিলেক্ট করুন</span>' },
    @{ p='<small>ডেলিভারি .*?প্রযোজ্য</small>'; r='<small>ডেলিভারি চার্জ প্রযোজ্য</small>' },
    @{ p='<h3>.*?সারাংশ</h3>'; r='<h3>অর্ডার সারাংশ</h3>' },
    @{ p='শ.*?অনলাইন পেমেন.*'; r='                শুধুমাত্র অনলাইন পেমেন্ট' },
    @{ p='.*?ডেলিভারি.*বাকি'; r='                অগ্রিম + ডেলিভারিতে বাকি' },
    @{ p='.*?অন ডেলিভারি'; r='                ক্যাশ অন ডেলিভারি' },
    @{ p='<span>.*?মূল্য</span>'; r='<span>পণ্যের মূল্য</span>' },
    @{ p='<span>ডেলিভারি .*?</span>'; r='<span>ডেলিভারি চার্জ</span>' },
    @{ p='<span>মোট .*?</span>'; r='<span>মোট দিতে হবে</span>' },
    @{ p='<span>.*?অগ.*?</span>'; r='<span>এখন অগ্রিম পরিশোধ করবেন</span>' },
    @{ p='<span>ডেলিভারি.*?দিতে হবে</span>'; r='<span>ডেলিভারির সময় দিতে হবে</span>' },
    @{ p='অর.*?কনফার.*?'; r='              অর্ডার কনফার্ম করুন' },
    @{ p='<small>আমাদের .*?ফোন করবে।</small>'; r='<small>আমাদের প্রতিনিধি অর্ডার কনফার্মেশনের জন্য আপনাকে ফোন করবে।</small>' },
    @{ p='placeholder="পূর.*?"'; r='placeholder="পূর্ণ নাম লিখুন"' },
    @{ p='<label>মোবাইল .*?\*</label>'; r='<label>মোবাইল নাম্বার *</label>' },
    @{ p='placeholder="১১ ডিজিট .*?"'; r='placeholder="১১ ডিজিট মোবাইল নাম্বার"' },
    @{ p='<label>.*?ডেলিভারি .*?\*</label>'; r='<label>পূর্ণ ডেলিভারি ঠিকানা *</label>' },
    @{ p='placeholder="বাড়ি/.*?" required'; r='placeholder="বাড়ি/ফ্ল্যাট, রাস্তার নাম, এরিয়া ইত্যাদি লিখুন" required' },
    @{ p='<label>অতিরিক.*?</label>'; r='<label>অতিরিক্ত নোট (যদি থাকে)</label>' },
    @{ p='placeholder=".*?ডেলিভারি.*?"\></textarea>'; r='placeholder="যেমন: সন্ধ্যায় ডেলিভারি, অফিসে ডেলিভারি ইত্যাদি"></textarea>' },
    @{ p='<label>শিপিং .*?\*</label>'; r='<label>শিপিং এরিয়া *</label>' },
    @{ p='<label for="payment_method">.*?</label>'; r='<label for="payment_method">পেমেন্ট মেথড নির্বাচন করুন *</label>' },
    @{ p='<option value="cod" selected>[\s\S]*?</option>'; r='<option value="cod" selected>\n                  ক্যাশ অন ডেলিভারি (ডেলিভারির সময় পেমেন্ট)\n              </option>' },
    @{ p='বিকাশ পেমেন.*'; r='                <option value="bkash">বিকাশ পেমেন্ট</option>' },
    @{ p='ShurjoPay \(অনলাইন পেমেন.*'; r='                <option value="shurjopay">ShurjoPay (অনলাইন পেমেন্ট)</option>' },
    @{ p='UddoktaPay \(অনলাইন পেমেন.*'; r='                <option value="uddoktapay">UddoktaPay (অনলাইন পেমেন্ট)</option>' },
    @{ p='<button type="submit" class="btn btn-primary">.*?</button>'; r='<button type="submit" class="btn btn-primary">অর্ডার সাবমিট করুন</button>' },
    @{ p='<p>.*?যোগাযোগ .*?</p>'; r='<p>অর্ডার করতে সমস্যা হলে বা প্রোডাক্ট সম্পর্কে জানতে আমাদের সাথে যোগাযোগ করুন।</p>' },
    @{ p='<button>মেসেঞ.*?</button>'; r='<button>মেসেঞ্জার</button>' },
    @{ p='<button>হোয়াটসঅ.*?</button>'; r='<button>হোয়াটসঅ্যাপ</button>' },
    @{ p='\{\!\! \$campaign_data->short_description \?\? ''.*?'' \!\!\}'; r='{!! $campaign_data->short_description ?? ''আমরা খুলনার আসল চুই ঝাল সারাদেশে পৌঁছে দিই। গুণগত মানে শতভাগ নিশ্চয়তা দিচ্ছি - একবার ট্রাই করলে পার্থক্য নিজেই বুঝবেন।'' !!}' },
    @{ p='<div class="footer-title">.*?লিংক</div>'; r='<div class="footer-title">দ্রুত লিংক</div>' },
    @{ p='<a href="#reviews">.*?</a>'; r='<a href="#reviews">কাস্টমার রিভিউ</a>' },
    @{ p='<a href="#order">.*?ফর.*?</a>'; r='<a href="#order">অর্ডার ফর্ম</a>' },
    @{ p='ফেইস ব.*?পেইজ'; r='ফেসবুক পেইজ' },
    @{ p='© সকল .*?ক্রিয়েটিভ ডিজাইন</span>'; r='© সকল কিছুর স্বত্বাধিকার {{ $generalsetting->name }} | সকল কারিগরি সহযোগিতায়: ক্রিয়েটিভ ডিজাইন</span>' },
    @{ p='alert\(".*?"\);'; r='alert("⚠️ অনুগ্রহ করে অন্তত একটি পণ্য সিলেক্ট করুন!");' }
)

foreach ($item in $replacements) {
    $text = [regex]::Replace($text, $item.p, $item.r)
}

[System.IO.File]::WriteAllText($path, $text, [System.Text.UTF8Encoding]::new($false))
Write-Output 'campaign updated'
